name: Build

on:
  workflow_dispatch:
    inputs:
      platform:
        description: 'Build Platform'
        required: true
        type: choice
        default: 'x64'
        options:
          - x64
          - x86
      configuration:
        description: 'Build Configuration'
        required: true
        type: choice
        default: 'Release'
        options:
          - Release
          - Debug
  workflow_call:
    inputs:
      platform:
        description: 'Build Platform'
        required: true
        type: string
        default: 'x64'
      configuration:
        description: 'Build Configuration'
        required: true
        type: string
        default: 'Release'
  pull_request:

env:
  BUILD_CONFIG: ${{ inputs.configuration || 'Release' }}
  PLATFORM: ${{ inputs.platform || 'x64' }}
  SOLUTION_FILE: ./WindowTool.sln
  PROJECT_FILE: ./WindowTool.vcxproj
  OUTPUT_DIR: ./bin/

jobs:
  build:
    name: Build Project
    runs-on: windows-latest

    steps:
    - name: Check Out Code
      uses: actions/checkout@v4

    - name: Setup Microsoft Build Engine
      uses: microsoft/setup-msbuild@v1

    - name: Build
      run: |
        msbuild `
          "/p:Configuration=${{ env.BUILD_CONFIG }}" `
          "/p:Platform=${{ env.PLATFORM }}" `
          "/p:OutDir=${{ env.OUTPUT_DIR }}${{ env.PLATFORM }}/" `
          "${{ env.PROJECT_FILE }}"

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.PLATFORM }}-artifact
        path: ${{ env.OUTPUT_DIR }}${{ env.PLATFORM }}/
