name: Publish

permissions: write-all
  
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version Number for Release'
        required: true
      configuration:
        description: 'Build Configuration'
        required: true
        type: choice
        default: 'Release'
        options:
          - Release
          - Debug
      body:
        description: 'Text for Release'
        required: false

jobs:
  build-x64:
    name: Build x64 Release
    uses: ./.github/workflows/build.yml
    with:
      platform: x64
      configuration: ${{ inputs.configuration }}

  build-x86:
    name: Build x86 Release
    uses: ./.github/workflows/build.yml
    with:
      platform: x86
      configuration: ${{ inputs.configuration }}

  publish:
    name: Publish Release
    runs-on: ubuntu-latest
    needs: [ build-x64, build-x86 ]
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download Artifacts
      uses: actions/download-artifact@v4
      with:
        pattern: '*-artifacts'
        merge-multiple: false

    - name: Upload Binaries to Release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ./*-artifacts
        file_glob: true
        tag: ${{ inputs.version }}
        overwrite: true
        body: ${{ inputs.body }}
